/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group1.booklend.views;

import java.sql.SQLException;

import group1.booklend.models.Book;

/**
 *
 * @author User
 */
public class AddNewBookView extends javax.swing.JFrame {

    private static AddNewBookView instance = null;

    /**
     * Creates new form AddNewBookView
     */
    private AddNewBookView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblAuthor = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BookLend - Add");
        setPreferredSize(new java.awt.Dimension(425, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(425, 450));
        getContentPane().setLayout(null);

        lblHeading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeading.setText("Add New Book");
        lblHeading.setToolTipText("");
        getContentPane().add(lblHeading);
        lblHeading.setBounds(6, 6, 120, 30);
        getContentPane().add(txtISBN);
        txtISBN.setBounds(10, 220, 370, 30);

        lblTitle.setText("Title");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(10, 60, 21, 16);

        lblISBN.setText("ISBN");
        getContentPane().add(lblISBN);
        lblISBN.setBounds(10, 200, 37, 16);
        getContentPane().add(txtTitle);
        txtTitle.setBounds(10, 80, 370, 30);

        lblAuthor.setText("Author");
        getContentPane().add(lblAuthor);
        lblAuthor.setBounds(10, 130, 37, 16);
        getContentPane().add(txtAuthor);
        txtAuthor.setBounds(10, 150, 370, 30);

        btnSave.setBackground(new java.awt.Color(51, 0, 51));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(300, 360, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
        String title = txtTitle.getText();
        String author = txtAuthor.getText();
        String isbn = txtISBN.getText();

        // Create a new book object
        Book book = new Book();
        book.setTitle(title);
        book.setAuthor(author);
        book.setIsbn(isbn);

        // Save the book object to database
        try {
            Book.create(book);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        // get DashboardView instance
        DashboardView dashboardView = DashboardView.getInstance();
        dashboardView.refreshBooksTable();

        // Close the window
        this.clearForm();
        this.dispose();

    }// GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewBookView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewBookView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewBookView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewBookView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewBookView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    public static AddNewBookView getInstance() {
        if (instance == null) {
            instance = new AddNewBookView();
        }
        return instance;
    }

    private void clearForm() {
        txtTitle.setText("");
        txtAuthor.setText("");
        txtISBN.setText("");
    }
}
