/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group1.booklend.views;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import group1.booklend.models.Book;
import group1.booklend.models.Loan;

/**
 *
 * @author User
 */
public class BookDetailView extends javax.swing.JFrame {

    private static BookDetailView instance = null;
    private Book book;

    public static BookDetailView getInstance() {
        if (instance == null) {
            instance = new BookDetailView();
        }
        return instance;
    }

    /**
     * Creates new form BookDetailView
     */
    private BookDetailView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                txtTitle = new javax.swing.JTextField();
                txtAuthor = new javax.swing.JTextField();
                txtISBN = new javax.swing.JTextField();
                lblTitle = new javax.swing.JLabel();
                lblAuthor = new javax.swing.JLabel();
                lblISBN = new javax.swing.JLabel();
                btnUpdate = new javax.swing.JButton();
                btnBorrow = new javax.swing.JButton();
                btnReturn = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblHistory = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Book Details");
                setBackground(new java.awt.Color(255, 255, 255));
                setPreferredSize(new java.awt.Dimension(520, 420));
                setResizable(false);
                setSize(new java.awt.Dimension(520, 420));
                getContentPane().setLayout(null);

                txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                txtTitle.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtTitleActionPerformed(evt);
                        }
                });
                getContentPane().add(txtTitle);
                txtTitle.setBounds(10, 30, 480, 30);

                txtAuthor.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtAuthorActionPerformed(evt);
                        }
                });
                getContentPane().add(txtAuthor);
                txtAuthor.setBounds(10, 90, 210, 22);
                getContentPane().add(txtISBN);
                txtISBN.setBounds(270, 90, 220, 22);

                lblTitle.setText("Title");
                getContentPane().add(lblTitle);
                lblTitle.setBounds(10, 10, 60, 16);

                lblAuthor.setText("Author");
                getContentPane().add(lblAuthor);
                lblAuthor.setBounds(10, 70, 60, 16);

                lblISBN.setText("ISBN");
                getContentPane().add(lblISBN);
                lblISBN.setBounds(270, 70, 25, 16);

                btnUpdate.setBackground(new java.awt.Color(51, 0, 51));
                btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                btnUpdate.setText("Update");
                btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUpdateActionPerformed(evt);
                        }
                });
                getContentPane().add(btnUpdate);
                btnUpdate.setBounds(410, 120, 75, 23);

                btnBorrow.setBackground(new java.awt.Color(0, 51, 0));
                btnBorrow.setForeground(new java.awt.Color(255, 255, 255));
                btnBorrow.setText("Borrow");
                btnBorrow.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBorrowActionPerformed(evt);
                        }
                });
                getContentPane().add(btnBorrow);
                btnBorrow.setBounds(250, 120, 72, 23);

                btnReturn.setBackground(new java.awt.Color(51, 0, 0));
                btnReturn.setForeground(new java.awt.Color(255, 255, 255));
                btnReturn.setText("Return");
                btnReturn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnReturnActionPerformed(evt);
                        }
                });
                getContentPane().add(btnReturn);
                btnReturn.setBounds(330, 120, 72, 23);

                tblHistory.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(tblHistory);

                getContentPane().add(jScrollPane1);
                jScrollPane1.setBounds(10, 150, 470, 240);

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
        book.returnBook();
        btnLogic();
        setTableData();
        DashboardView.getInstance().refreshBooksTable();
    }// GEN-LAST:event_btnReturnActionPerformed

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBorrowActionPerformed
        BorrowView.getInstance().setBook(book);
        BorrowView.getInstance().setVisible(true);
    }// GEN-LAST:event_btnBorrowActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed

        book.setTitle(txtTitle.getText());
        book.setAuthor(txtAuthor.getText());
        book.setIsbn(txtISBN.getText());

        try {
            Book.update(book);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        DashboardView.getInstance().refreshBooksTable();
    }// GEN-LAST:event_btnUpdateActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTitleActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtAuthorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookDetailView().setVisible(true);
            }
        });
    }

    public void setBook(Book book) {
        this.book = book;
        setTableData();
        loadBook();
        btnLogic();
    }

    private void loadBook() {
        txtTitle.setText(book.getTitle());
        txtAuthor.setText(book.getAuthor());
        txtISBN.setText(book.getIsbn());
    }

    public void setTableData() {
        List<Loan> loans;
        loans = Loan.byBook(book);

        String[] columnNames = { "ID", "Borrower", "Borrow Date", "Return Date" };
        Object[][] data = new Object[loans.size()][columnNames.length];
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        for (int i = 0; i < loans.size(); i++) {
            Loan loan = loans.get(i);
            data[i][0] = loan.getId();
            data[i][1] = loan.getBorrower().getName();
            data[i][2] = sdf.format(loan.getBorrow_date());
            data[i][3] = loan.getReturn_date() == null ? "Not returned" : sdf.format(loan.getReturn_date());
        }

        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tblHistory.setModel(model);
    }

    public void btnLogic() {
        if (!book.isLoaned()) {
            btnBorrow.setEnabled(true);
            btnReturn.setEnabled(false);
        } else {
            btnBorrow.setEnabled(false);
            btnReturn.setEnabled(true);
        }
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBorrow;
        private javax.swing.JButton btnReturn;
        private javax.swing.JButton btnUpdate;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblAuthor;
        private javax.swing.JLabel lblISBN;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JTable tblHistory;
        private javax.swing.JTextField txtAuthor;
        private javax.swing.JTextField txtISBN;
        private javax.swing.JTextField txtTitle;
        // End of variables declaration//GEN-END:variables
}
